spring:
  data:
    mongodb:
      uri: mongodb://root:85857855@localhost:28000/drools?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mi-grupo-consumidor
      #auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  webflux:
    base-path: /oc/graphql
